# Generated by Django 4.0.5 on 2022-07-23 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=85)),
                ('country', models.CharField(blank=True, max_length=85)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('zip_code', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='UsersLocations',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('unit', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations_city', to='base.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'city')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ManyToManyField(through='base.UsersLocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ForecastNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=3)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temperature_max', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temperature_min', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temperature_unit', models.CharField(blank=True, max_length=10)),
                ('humidity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_forecast_now', to='base.location')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastHourly',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('feels_like', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('temperature_unit', models.CharField(blank=True, max_length=10)),
                ('humidity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_forecast_hourly', to='base.location')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('city', 'country_code')},
        ),
    ]
