# Generated by Django 4.0.5 on 2022-07-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user_searched_locations',
        ),
        migrations.RemoveField(
            model_name='userslocations',
            name='name',
        ),
    ]
