# Generated by Django 4.0.5 on 2022-06-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_location_alter_note_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=85)),
                ('country', models.CharField(blank=True, max_length=85)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('latitude', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('longitude', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('zip_code', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'unique_together': {('name', 'country_code')},
            },
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
