# Generated by Django 4.0.5 on 2022-07-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_location_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userslocations',
            options={'verbose_name': 'userlocations'},
        ),
    ]
