# Generated by Django 4.0.5 on 2022-07-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_userslocations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userslocations',
            options={'verbose_name': 'userlocation'},
        ),
    ]
