# Generated by Django 4.0.5 on 2022-07-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_city_users_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='users_location',
            field=models.ManyToManyField(to='base.usersearchlocation'),
        ),
    ]
