# Generated by Django 4.0.5 on 2022-07-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_city_users_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='users_location',
        ),
    ]
