# Generated by Django 4.0.5 on 2022-07-14 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_city_users_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user_searched_locations',
        ),
    ]
