# Generated by Django 4.0.5 on 2022-07-14 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0007_remove_city_user_searched_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user_searched_locations',
            field=models.ManyToManyField(blank=True, related_name='cities', through='base.UsersLocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
