# Generated by Django 4.0.5 on 2022-07-24 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_userslocations_location_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
    ]
