# Generated by Django 4.0.5 on 2022-07-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_city_name_usersearchlocation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='tag',
            new_name='tags',
        ),
    ]
