# Generated by Django 4.0.5 on 2022-07-24 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_remove_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ManyToManyField(through='base.UsersLocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
