# Generated by Django 4.0.5 on 2022-07-14 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0010_rename_tag_city_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='tags',
        ),
        migrations.AddField(
            model_name='city',
            name='userTag',
            field=models.ManyToManyField(blank=True, related_name='user_search_cities', through='base.UsersLocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserSearchLocation',
        ),
    ]
