# Generated by Django 4.0.5 on 2022-07-14 23:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_remove_city_tags_city_usertag_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userslocations',
            unique_together={('user', 'city')},
        ),
    ]
