# Generated by Django 4.0.6 on 2022-08-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_forecastnow_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecastnow',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_forecast_now', to='base.location'),
        ),
    ]
