# Generated by Django 4.0.5 on 2022-07-15 01:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0013_remove_city_usertag_city_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='user',
        ),
        migrations.AddField(
            model_name='city',
            name='userTag',
            field=models.ManyToManyField(blank=True, related_name='user_search_cities', through='base.UsersLocations', to=settings.AUTH_USER_MODEL),
        ),
    ]
